### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by coolaj86** [dashhive/crowdnode.js#2]
- [x] Generate a Dash Wallet
- [x] Send monies to Dash Address <span>#</span>1 the boring way
- [x] Check UTXOs
- [ ] ❌ ~~Check SmartSendRate~~
- [x] Calculate ~~ideal~~ few inputs (not all inputs)
- [x] Sign Message to Dash Address <span>#</span>2
- [x] Send RawTx to Dash Address <span>#</span>2
- [x] Send from <span>#</span>2 to Hot Wallet to Sign Up
- [x] Send from <span>#</span>2 to Hot Wallet to Agree
- [x] Send deposit
- [x] Commands to check stats
- [x] Listen for payment events via WebSocket
- [x] limit debug output with `debug: true` option
- [ ] ❌ ~~Whilst command is running, auto-forward new payments to Hot Wallet~~
- [x] Withdrawal rewards
- [x] Unstake

# Finishing Touches

- [x] ditch insightApi.getBalance for txes-based utxo checking
- [x] Keep enough change to run a withdrawal (prime the pump)
- [x] Show amounts when sending all-the-money
- [ ] Documentation
- [ ] Do-all-the-things-at-once command?
- [ ] Publish to npm

## Other

- [ ] PR bad JSDoc in `dashcore-lib/lib/transaction/transaction.js`

**Comment by coolaj86** [comment]
```bash
git clone git@github.com:therootcompany/merchant-wallet.js.git
pushd ./merchant-wallet.js/
npm ci --only=production
```

```bash
./bin/mnemonic-to-secret-env.sh
./bin/xpubkey-to-env.sh
```

**Comment by coolaj86** [comment]
# WebSocket Notes:

- `t=xxxx`: https://stackoverflow.com/a/48633718

**Comment by coolaj86** [comment]
Maybe use <https://github.com/trezor/blockbook/blob/master/docs/api.md>

**Comment by coolaj86** [comment]
```bash
crowdnode stake # do it all
```

```bash
crowdnode generate # Xxxxxxxxx.wif
crowdnode select "0'/1/20" # from mnemonic
crowdnode signup ./Xxxxxxxxx.wif
crowdnode accept ./Xxxxxxxxx.wif
crowdnode deposit ./Xxxxxxxxx.wif # with optional amount
crowdnode withdrawal ./Xxxxxxxxx.wif 1000 # with optional amount
```
